//  切换歌曲URL
export const CHANGE_SONG_URL = 'CHANGE_SONG_URL'
// 切换歌曲详情
export const CHANGE_SONG_DETAIL = 'CHANGE_SONG_DETAIL'
// 当前歌曲坐标
export const CHANGE_CURRENTINDEX = 'CHANGE_CURRENTINDEX'
// 播放列表
export const CHANGE_PLAYLIST = 'CHANGE_PLAYLIST'
// 播放模式
export const CHANGE_PLAYPATTERN = 'CHANGE_PLAYPATTERN'
// 改变歌词
export const CHANGE_LYRICLIST = 'CHANGE_LYRICLIST'
// 保存当前播放歌词
export const CHANGE_CURRENTLYRIC = 'CHANGE_CURRENTLYRIC'
